eden_conception/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as v
from django.conf.urls.static import static
from django.views.i18n import JavaScriptCatalog


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('static_page.urls', namespace='static_page')),
    path('', include('user.urls', namespace='user')),
    path('', include('project.urls', namespace='project')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path(
        'reset_password/',
        v.PasswordResetView.as_view(template_name='user/password_reset.html'),
        name='password_reset'),
    path(
        'reset/<uidb64>/<token>/',
        v.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path(
        'reset_password_sent/',
        v.PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),
        name='password_reset_done'),
    path(
        'reset_password_complete/',
        v.PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'),
        name='password_reset_complete'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

project/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as v
from project.views.project_views import ProjectView
from project.views.list_views import ListView
from project.views.task_views import TaskView


app_name = 'project'

urlpatterns = [
    path('dashboard/', login_required(ProjectView.as_view(), login_url='user:login'), name='dashboard'),
    path('create_project/', login_required(ProjectView.create_project, login_url='user:login'), name='create_project'),
    path('delete_project/', login_required(ProjectView.delete_project, login_url='user:login'), name='delete_project'),
    path('add_member/', login_required(ProjectView.add_member, login_url='user:login'), name='add_member'),
    path('update_project/', login_required(ProjectView.update_project, login_url='user:login'), name='update_project'),
    path('<project_id>/update_form/', login_required(ProjectView.as_view(), login_url='user:login'), name='form_update_project'),
    path('get_statistics/', login_required(ProjectView.get_statistics, login_url='user:login'), name='get_statistics'),

    path('project-<int:project_id>/', login_required(ListView.as_view(), login_url='user:login'), name='project'),
    path('create_list/', login_required(ListView.create_list, login_url='user:login'), name='create_list'),
    path('delete_list/', login_required(ListView.delete_list, login_url='user:login'), name='delete_list'),
    path('update_list/', login_required(ListView.update_list, login_url='user:login'), name='update_list'),
    path('<list_id>/update_list_form/', login_required(ListView.as_view(), login_url='user:login'), name='form_update_list'),
    path('create_task/', login_required(ListView.create_task, login_url='user:login'), name='create_task'),
    path('update_order_task/', login_required(ListView.update_order_task, login_url='user:login'), name='update_task'),

    path('project-<int:project_id>/task-<int:task_id>/', login_required(TaskView.as_view(), login_url='user:login'), name='task'),
    path('<task_id>/update/', login_required(TaskView.as_view(), login_url='user:login'), name='form_update_task'),
    path('update_task/', login_required(TaskView.update_task, login_url='user:login'), name='update_task'),
    path('delete_task/', login_required(TaskView.delete_task, login_url='user:login'), name='delete_task'),
]

user/urls.py
# django.contrib.auth import urls
from django.db.models import base
from django.urls import path, include
from django.contrib.auth import views as v
from . import views


app_name = 'user'
urlpatterns = [
    path('login/', v.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('register/', views.RegisterView.as_view(), name='register'),
]

project/forms/list_forms.py
''' Forms for model List '''
from django import forms
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _
from project.models.list import List


class CreateListForm(forms.Form):
    ''' Form to create a List '''
    list_name = forms.CharField(label=_('List name'), max_length=100)


class UpdateListForm(ModelForm):
    ''' Form to update the list's name '''

    class Meta:
        ''' Class Meta is used to target the model and her field '''
        model = List
        fields = ['name']

project/forms/project_forms.py
''' Forms to the model Project '''
from django import forms
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _
from user.models import User
from project.models.project import Project


class CreateProjectForm(forms.Form):
    ''' Form used to create a project '''
    project_name = forms.CharField(label=_('Project name'), max_length=100)


class AddMember(forms.Form):
    ''' From used to add a member into a project '''

    def __init__(self, request, *args, **kwargs):
        super(AddMember, self).__init__(*args, **kwargs)
        user = User.objects.get(id=request.user.id)
        projects = user.main_user.all()
        self.fields['project_name'] = forms.ModelChoiceField(queryset=projects, empty_label=None)

    member_email = forms.CharField(label=_('Member Email'), max_length=100)


class UpdateProjectForm(ModelForm):
    ''' Form used to update the project's name '''

    class Meta:
        ''' Class Meta is used to target the model and her field '''
        model = Project
        fields = ['name']

project/forms/task_forms.py
''' Forms to the model Task '''
from django import forms
from django.forms import ModelForm, DateField
from django.utils.translation import gettext_lazy as _
from project.models.list import List
from project.models.task import Task
from .widgets import HourField


class CreateTaskForm(forms.Form):
    ''' Form to create a task '''
    task_name = forms.CharField(label=_('Task name'), max_length=100)


class UpdateTaskForm(ModelForm):
    ''' Form to update a task '''
    deadline = DateField(input_formats=['%d/%m/%Y'], required=True, label=_('Deadline'))

    def __init__(self, instance, *args, **kwargs):
        super(UpdateTaskForm, self).__init__(*args, **kwargs)
        project = List.objects.get(pk=instance.project_list.id).project
        self.fields['assigned_to'] = forms.ModelChoiceField(
            queryset=project.user_ids.all(),
            empty_label=None,
            label=_('Assigned to')
        )
        self.fields['planned_hours'] = HourField(label=_('Planned hours'))

    class Meta:
        ''' Class Meta is used to target the model and her fields '''

        model = Task
        fields = ['name', 'assigned_to', 'deadline', 'description', 'planned_hours']

project/forms/widgets.py
''' Widget to manipulate float fields in hours '''
import math
import re
from django import forms
from django.forms import widgets
from django.core.exceptions import ValidationError



class HourWidget(widgets.TextInput):
    ''' This widget manipulate a field float in hour '''

    def _format_value(self, value):
        if isinstance(value, (float, int)):
            hours = math.floor(value)
            minutes = (value - hours) * 60
            value = f'{int(hours):02d}:{int(minutes):02d}'

        return value

    def render(self, name, value, attrs=None, renderer=None):
        value = self._format_value(value)
        return super(HourWidget, self).render(name, value, attrs)

    def _has_changed(self, initial, data):
        return super(HourWidget, self)._has_changed(self._format_value(initial), data)


class HourField(forms.Field):
    ''' This class create a new field for a form '''
    widget = HourWidget

    def clean(self, value):
        super(HourField, self).clean(value)

        match = re.match("^([0-9]{1,2}):([0-9]{2})$", value)
        if not match:
            raise ValidationError("Please enter a valid hour ( ex: 12:34 )")

        groups = match.groups()
        hour = float(groups[0])
        minutes = float(groups[1])

        if minutes >= 60:
            raise ValidationError("Invalid value for minutes")

        return hour + minutes / 60

project/views/list_views.py
""" All views for the model list """
import json
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.utils.translation import gettext_lazy as _

from project.forms.list_forms import CreateListForm, UpdateListForm
from project.forms.task_forms import CreateTaskForm
from project.models.project import Project
from project.models.list import List
from project.models.task import Task
from user.models import User


class ListView(View):
    ''' Class to manage all interactions and views with the lists '''

    template_name = 'project/lists/lists.html'
    form = CreateListForm

    def get(self, request, project_id):
        ''' Method to view all lists of project choosen. '''

        project = get_object_or_404(Project, pk=project_id)
        lists = project.list_set.all()

        context = {
            'project': project,
            'lists': lists,
            'create_list_form': self.form,
            'create_task_form': CreateTaskForm
        }
        return render(request, self.template_name, context)

    def post(self, request, list_id):
        ''' Method post to display the form
            to update a list.
        '''
        res = {}
        if request.method == 'POST':
            current_list = List.objects.get(id=list_id)
            datas = {'name': current_list.name}

            form_update = UpdateListForm(instance=current_list, initial=datas)
            context = {'form_update': form_update, 'list': current_list}
            res['list_id'] = list_id
            res['template'] = render_to_string(
                template_name='project/lists/forms/update_list.html',
                context=context,
                request=request
            )

        return JsonResponse(res)

    @classmethod
    def create_list(cls, request):
        ''' method to create a list.'''
        res = {}
        context = {}
        form = cls.form(request.POST)
        if form.is_valid():
            name = form.cleaned_data['list_name']
            project = Project.objects.get(id=request.POST.get('project_id'))

            new_list = List.objects.create(
                name=name,
                project=project,
            )
            project.save()

            context['new_list'] = new_list
            context['create_task_form'] = CreateTaskForm

            res['list_name'] = name
            res['list_id'] = new_list.id
            res['template'] = render_to_string(
                template_name='project/lists/new_list.html',
                context=context,
                request=request
            )
        else:
            res['error'] = _('Please, write a list name.')

        return JsonResponse(res)

    @staticmethod
    def delete_list(request):
        ''' method to delete a list.'''
        res = {}
        if request.method == 'POST':
            list_to_delete = List.objects.get(id=request.POST.get('list_id'))
            project = Project.objects.get(id=list_to_delete.project_id)

            list_to_delete.delete()
            project.save()

            res['list_id'] = request.POST.get('list_id')
            res['success'] = _('The list has been deleted')
        else:
            res['error'] = _('The list doesn\'t have deleted')

        return JsonResponse(res)

    @staticmethod
    def create_task(request):
        ''' method to create a task.'''
        res = {}
        if request.method == 'POST':
            user = User.objects.get(id=request.user.id)
            name = request.POST.get('task_name')
            list_id = request.POST.get('list_id')
            current_list = List.objects.get(id=int(list_id))
            project = Project.objects.get(id=current_list.project_id)

            index = Task.objects_task.get_index(current_list)
            new_task = Task.objects.create(
                name=name,
                project_list=current_list,
                assigned_to=user,
                deadline=None,
                index=index,
                planned_hours=0.0,
            )
            project.save()

            context = {'task': new_task, 'project': project}

            res['task_name'] = name
            res['task_id'] = new_task.id
            res['list_id'] = list_id
            res['template'] = render_to_string('project/tasks/new_task.html', context)

        return JsonResponse(res)

    @staticmethod
    def update_order_task(request):
        ''' method to update the order of task.
            Called when we drag and drop a task into
            an another list.
        '''
        res = {}
        if request.method == 'POST':
            datas = json.loads(request.POST.get('datas'))
            Task.objects_task.update_order_task(datas)

        return JsonResponse(res)

    @staticmethod
    def update_list(request):
        ''' Method to update the name of list. '''
        res = {}
        if request.method == 'POST':
            current_list = List.objects.get(id=request.POST.get('list_id'))

            # Update list
            current_list.name = request.POST.get('name')
            current_list.save()

            res['list_id'] = current_list.id
            res['list_name'] = current_list.name

        return JsonResponse(res)

project/views/task_views.py
""" All views for the model task """
from datetime import datetime
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.utils.translation import gettext_lazy as _

from project.forms.task_forms import UpdateTaskForm
from project.models.project import Project
from project.models.task import Task
from user.models import User
from timesheet.views.timesheet_views import TimesheetView


class TaskView(View):
    ''' Class to manage all interactions and views with the tasks. '''
    template_name = 'project/tasks/tasks.html'

    def get(self, request, project_id, task_id):
        ''' Method to view the detail of a task. '''
        project = get_object_or_404(Project, pk=project_id)
        task = get_object_or_404(Task, pk=task_id)
        context = {'project': project, 'task': task}

        return render(request, self.template_name, context)

    def post(self, request, task_id):
        ''' Method to display the form to update one task '''
        res = {}
        if request.method == 'POST':
            current_task = Task.objects.get(id=task_id)
            datas = {
                'name': current_task.name,
                'assigned_to': current_task.assigned_to,
                'deadline': current_task.deadline,
                'description': current_task.description,
                'planned_hours': current_task.planned_hours
            }

            form_update = UpdateTaskForm(instance=current_task, initial=datas)
            context = {
                'form_update': form_update,
                'formset': TimesheetView.create_formset(current_task),
                'task': current_task
            }

            res['task_id'] = task_id
            res['template'] = render_to_string(
                template_name='project/tasks/forms/update_task.html',
                context=context,
                request=request
            )

        return JsonResponse(res)

    @staticmethod
    def update_task(request):
        ''' Method to update a task. '''
        res = {}
        if request.method == 'POST':
            current_task = Task.objects.get(id=request.POST.get('task_id'))
            formset = TimesheetView.update_timesheet(request)

            if formset is not True:
                formset_clean = [i for i in formset if i]
                if formset_clean:
                    res['error'] = formset_clean[0]

            # Convert time to float
            convert_in_time = datetime.strptime(request.POST.get('planned_hours'), '%H:%M').time()
            planned_hours_float = convert_in_time.hour + convert_in_time.minute / 60.0

            # Update task
            current_task.name = request.POST.get('name')
            current_task.assigned_to = User.objects.get(id=request.POST.get('assigned_to'))
            current_task.deadline = datetime.strptime(request.POST.get('deadline'), '%d/%m/%Y')
            current_task.description = request.POST.get('description')
            current_task.planned_hours = planned_hours_float
            current_task.save()

            context = {'task': current_task}

            res['task_id'] = current_task.id
            res['template'] = render_to_string('project/tasks/task_detail.html', context)

        return JsonResponse(res)

    @staticmethod
    def delete_task(request):
        ''' Method to delete a task. '''
        res = {}
        if request.method == 'POST':
            task_to_delete = Task.objects.get(id=request.POST.get('task_id'))
            project = Project.objects.get(id=task_to_delete.project_list.project_id)

            task_to_delete.delete()
            project.save()

            res['task_id'] = request.POST.get('task_id')
            res['project_id'] = project.id
            res['success'] = _('The task has been deleted')
        else:
            res['error'] = _('The task doesn\'t have deleted')

        return JsonResponse(res)

project/templates/project/projects/project_detail.html
{% load static %}
{% load i18n %}
{% for project in projects %}
    <div id="project-detail-{{project.id}}" class="d-none project-detail">
        <div class="header-project-detail">
            <h2>{{project.name}}</h2>
            <div class="icons-p">
                {% if project.user_id == user.id %}
                    <div class="edit-project">
                        <i id="edit-project-{{project.id}}" project-id="{{project.id}}" class="fas fa-pencil-alt"></i>
                    </div>
                {% endif %}
                <div class="view-project">
                    <a href="/project-{{project.id}}">
                        <i class="far fa-eye"></i>
                    </a>
                </div>
                {% if project.user_id == user.id %}
                    <div class="delete-project">
                        <form method="post" class="form-delete-project">
                            {% csrf_token %}
                            <input type="hidden" name="project_id" value="{{ project.id }}">
                            <button type="submit"><i class="far fa-trash-alt"></i></button>
                        </form>
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="main-info">
            <div class="last-modification">
                <h2>{% translate 'Last modification:' %}</h2>
                <span>{{project.last_modified}}</span>
            </div>
            <div class="task-count">
                <h2>{% translate 'Task number:' %}</h2>
                <span class="nb_tasks">{{project.get_number_task}}</span>
            </div>
            <div class="main-user">
                <h2>{% translate 'Created by:' %}</h2>
                <span>{{project.user.first_name}}</span>
            </div>
        </div>
        <div class="statistics-project">
            <div class="flex-stats">
                <div id="project-nb-task-by-list-{{project.id}}" class="statistics-project-nb-task-by-list contain-stats"></div>
                <div id="project-history-{{project.id}}" class="statistics-project-history contain-stats"></div>
            </div>
            <div id="project-planned-hour-{{project.id}}" class="statistics-project-planned-hour contain-stats"></div>
        </div>
    </div>
{% endfor %}

project/templates/project/projects/projects.html
{% extends 'project/base.html' %}
{% load i18n %}
{% load sass_tags %}
{% load static %}
{% block title %}Dashboard{% endblock %}
{% block scss %}
    <link href="{% sass_src 'scss/base_back.scss' %}" rel="stylesheet" type="text/css" />
    <link href="{% sass_src 'scss/project_detail.scss' %}" rel="stylesheet" type="text/css" />
    <link href="{% sass_src 'scss/personal_space.scss' %}" rel="stylesheet" type="text/css" />

    <!-- AmCharts Library -->
    <script src="https://cdn.amcharts.com/lib/4/core.js"></script>
    <script src="https://cdn.amcharts.com/lib/4/charts.js"></script>
    <script src="https://cdn.amcharts.com/lib/4/themes/dataviz.js"></script>
    <script src="https://cdn.amcharts.com/lib/4/themes/animated.js"></script>
{% endblock %}
{% block content %}
    <header>
        <div id="dash-modal" class="modal"></div>
        <div class="logout">
            <a class="personal_space"><i class="fas fa-user"></i></a>
            <a href="{% url 'user:logout' %}"><i class="fas fa-sign-out-alt"></i></a>
        </div>
        <nav>
            <h2>
                <i class="fas fa-folder"></i>
                {% translate 'Projects' %}
                <i id="btn-create-project" class="fas fa-plus"></i>
            </h2>
            <ul class="project-list">
                {% if projects %}
                    {% for project in projects %}
                        <li><h4 project-id="{{project.id}}">{{ project.name }}</h4></li>
                    {% endfor %}
                {% endif %}
            </ul>
            <h2>
                <i class="fas fa-users"></i>
                {% translate 'Collaborator' %}
                <i id="btn-add-member" class="fas fa-plus"></i>
            </h2>
            <ul class="member-list">
                {% for member in  members %}
                    <li><h4 member-id="{{member.id}}">{{ member.first_name }}</h4></li>
                {% endfor %}
            </ul>
        </nav>
    </header>
    <main>
        <section class="element-dashboard is-height">
            <div class="container-projects-details d-none">
                {% include 'project/projects/project_detail.html' %}
            </div>
            <div class="container-create-project" id="container-create-project">
                {% include 'project/projects/forms/create_project.html' %}
            </div>
            <div class="container-add-member closed" id="container-add-member">
                {% include 'project/projects/forms/add_member.html' %}
            </div>
            <div class="container-info-user closed" id="container-info-user">
                {% include 'user/personal_space.html' %}
            </div>
            <div class="container-info-member closed" id="container-info-member">
                {% include 'user/personal_space_member.html' %}
            </div>
        </section>
    </main>

{% endblock %}
{% block js %}
    <script src="{% url 'javascript-catalog' %}"></script>
    <script src="{% static 'js/submit_form_ajax.js' %}"></script>
    <script src="{% static 'js/personal_space.js' %}"></script>
    <script src="{% static 'js/projects/statistics.js' %}"></script>
    <script src="{% static 'js/projects/project_detail.js' %}"></script>
    <script src="{% static 'js/projects/create_project.js' %}"></script>
    <script src="{% static 'js/projects/update_project.js' %}"></script>
    <script src="{% static 'js/projects/delete_project.js' %}"></script>
    <script src="{% static 'js/projects/add_member.js' %}"></script>
    <script>
        viewDashboard();
    </script>
{% endblock %}