eden_conception/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as v
from django.conf.urls.static import static
from django.views.i18n import JavaScriptCatalog


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('static_page.urls', namespace='static_page')),
    path('', include('user.urls', namespace='user')),
    path('', include('project.urls', namespace='project')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path(
        'reset_password/',
        v.PasswordResetView.as_view(template_name='user/password_reset.html'),
        name='password_reset'),
    path(
        'reset/<uidb64>/<token>/',
        v.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path(
        'reset_password_sent/',
        v.PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),
        name='password_reset_done'),
    path(
        'reset_password_complete/',
        v.PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'),
        name='password_reset_complete'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

user/urls.py
# django.contrib.auth import urls
from django.db.models import base
from django.urls import path, include
from django.contrib.auth import views as v
from . import views


app_name = 'user'
urlpatterns = [
    path('login/', v.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('register/', views.RegisterView.as_view(), name='register'),
]

user/models.py
""" Inherit AbstractUser to add attributes """
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    ''' Inherit AbstractUser and add new fields '''
    email = models.EmailField(
        _('email address'),
        blank=True,
        unique=True,
        max_length=100
    )
    image = models.ImageField(default='default.png', blank=True, upload_to='media')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

user/forms.py
''' Forms to the user application '''
from django import forms
from django.contrib.auth.forms import UserCreationForm
from user.models import User


class UserCreationFormInherit(UserCreationForm):
    ''' Inherit the form class to create a user '''

    class Meta(UserCreationForm.Meta):
        ''' Add the new fields create in the inherit model user
            to the form for create a user.
        '''
        model = User
        new_fields = ('first_name', 'last_name', 'email', 'image')
        fields = UserCreationForm.Meta.fields + new_fields

user/views.py
""" All views for the user application """
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import login, logout
from django.contrib.auth.views import LogoutView
from django.core.files.storage import default_storage
from .forms import UserCreationFormInherit
from .models import User


class RegisterView(View):

    template_name = 'user/register.html'
    form_class = UserCreationFormInherit

    def get(self, request):
        ''' Method to display the page contains the register form '''
        context = {'form': self.form_class}
        return render(request, self.template_name, context)

    def post(self, request):
        ''' Method to manage the submit register form '''
        if request.method == 'POST':
            if 'image' in request.FILES:
                form = self.form_class(request.POST, request.FILES)
            else:
                form = self.form_class(request.POST)

            if form.is_valid():
                username = form.cleaned_data['username']
                first_name = form.cleaned_data['first_name']
                last_name = form.cleaned_data['last_name']
                email = form.cleaned_data['email']
                password1 = form.cleaned_data['password1']

                user = User.objects.filter(email=email)
                if not user.exists():
                    if request.FILES:
                        file = request.FILES['image']
                        image = default_storage.save(file.name, file)
                        user = User.objects.create_user(
                            username=username,
                            first_name=first_name,
                            last_name=last_name,
                            image=image,
                            email=email,
                            password=password1,
                        )
                    else:
                        user = User.objects.create_user(
                            username=username,
                            first_name=first_name,
                            last_name=last_name,
                            email=email,
                            password=password1,
                        )
                else:
                    user = user.first()

                login(request, user)
                return redirect('project:dashboard')

        return render(
            request,
            self.template_name,
            {'form': self.form_class(request.POST, request.FILES)}
        )


class LogoutView(LogoutView):
    """ Class View to deconnect user """

    def get(self, request):
        logout(request)

        return redirect('user:login')

user/templates/user/login.html
{% extends 'static_page/base.html' %}
{% load i18n %}
{% load sass_tags %}
{% block scss %}<link href="{% sass_src 'scss/account.scss' %}" rel="stylesheet" type="text/css"/>{% endblock %}
{% block content %}
<a href="/" class="return-home"><i class="fas fa-arrow-left"></i></a>
<section class="main-form">
    <div class="container-form">
        <h1>{% translate 'Sign in' %}</h1>
        <form method="post" action="{% url 'user:login' %}">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    <label class="col-6" for="{{field.id_for_label}}">
                        {{ field.label }}
                    </label>
                    {{ field }}
                </div>
            {% endfor %}
            {% if form.errors %}
                <div class="alert alert-danger">
                    {% for key, value in form.errors.items %}
                        <p>{{ value }}</p>
                    {% endfor %}
                </div>
            {% endif %}
            <div class="m-auto">
                <button class="" id="id_login" type="submit">{% translate 'Sign in' %}</button>
            </div>
            <input type="hidden" name="next" value="{{ redirect_field_name }}" />
        </form>
        <p><a href="{% url 'user:register' %}">{% translate 'No account ?' %}</a></p>
        <p><a href="">{% translate 'Forgot your password ?' %}</a></p>
    </div>
</section>
{% endblock %}

user/templates/user/password_reset.html
{% extends 'static_page/base.html' %}
{% load i18n %}
{% load sass_tags %}
{% block scss %}<link href="{% sass_src 'scss/account.scss' %}" rel="stylesheet" type="text/css"/>{% endblock %}
{% block content %}
<a href="/" class="return-home"><i class="fas fa-arrow-left"></i></a>
<section class="main-form">
    <div class="container-form">
        <h1>{% translate 'Reset password' %}</h1>
        <p>{% translate "Enter your email address below, and we'll email instructions for setting a new one." %}</p>
        <form method="POST">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    <label class="col-6" for="{{field.id_for_label}}">
                        {{ field.label }}
                    </label>
                    {{ field }}
                </div>
            {% endfor %}
            {% if form.errors %}
                <div class="alert alert-danger">
                    {% for key, value in form.errors.items %}
                        <p>{{ value }}</p>
                    {% endfor %}
                </div>
            {% endif %}
            <div class="m-auto">
                <button id="password_reset_btn" type="submit">{% translate 'Password reset' %}</button>
            </div>
        </form>
    </div>
</section>
{% endblock %}

user/templates/user/password_reset_complete.html
{% extends 'static_page/base.html' %}
{% load i18n %}
{% load sass_tags %}
{% block scss %}<link href="{% sass_src 'scss/account.scss' %}" rel="stylesheet" type="text/css"/>{% endblock %}
{% block content %}
<a href="/" class="return-home"><i class="fas fa-arrow-left"></i></a>
<section class="main-form">
    <div class="container-form">
        <h1>{% translate 'Password validate' %}</h1>
        <p>{% translate 'Your password has been set.' %}</p>
        <p><a href="{% url 'user:login' %}">{% translate 'Sign In Here' %}</a></p>
    </div>
</section>
{% endblock %}

user/templates/user/password_reset_confirm.html
{% extends 'static_page/base.html' %}
{% load i18n %}
{% load sass_tags %}
{% block scss %}<link href="{% sass_src 'scss/account.scss' %}" rel="stylesheet" type="text/css"/>{% endblock %}
{% block content %}
<a href="/" class="return-home"><i class="fas fa-arrow-left"></i></a>
<section class="main-form">
    <div class="container-form">
        <h1>{% translate 'New password' %}</h1>
        <form method="POST">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    <label class="col-6" for="{{field.id_for_label}}">
                        {{ field.label }}
                    </label>
                    {{ field }}
                </div>
            {% endfor %}
            {% if form.errors %}
                <div class="alert alert-danger">
                    {% for key, value in form.errors.items %}
                        <p>{{ value }}</p>
                    {% endfor %}
                </div>
            {% endif %}
            <div class="m-auto">
                <button class="" type="submit">{% translate 'Reset Password' %}</button>
            </div>
        </form>
    </div>
</section>
{% endblock %}

user/templates/user/password_reset_done.html
{% extends 'static_page/base.html' %}
{% load i18n %}
{% load sass_tags %}
{% block scss %}<link href="{% sass_src 'scss/account.scss' %}" rel="stylesheet" type="text/css"/>{% endblock %}
{% block content %}
<a href="/" class="return-home"><i class="fas fa-arrow-left"></i></a>
<section class="main-form">
    <div class="container-form">
        <h1>{% translate 'Sent email' %}</h1>
        <p>{% translate "An email has been sent with instructions to reset your password." %}</p>
    </div>
</section>
{% endblock %}

user/templates/user/personal_space.html
{% load static %}
{% load i18n %}
<div id="user-detail-{{user.id}}" class="user-detail">
    <div class="header-user-detail">
        <h2>{{user.first_name}}</h2>
        <img class="user_image" src="{{ user.image.url }}" alt="profil image">
    </div>
    <div class="main-info">

    </div>
</div>

user/templates/user/personal_space_member.html
{% load static %}
{% load i18n %}
{% for member in members %}
    <div id="member-detail-{{member.id}}" class="d-none member-detail">
        <div class="header-member-detail">
            <h2>{{member.first_name}}</h2>
            <img class="user_image" src="{{ member.image.url }}" alt="profil image">
        </div>
        <div class="main-info">
            <div class="projects-member">
                <h2>{% translate 'Guest on:' %}</h2>
                <ul class="list-project-member">
                    {% for project in member.member.all %}
                        {% if project.user_id == user.id %}
                            <li> - {{project.name}}</li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endfor %}

user/templates/user/register.html
{% extends 'static_page/base.html' %}
{% load i18n %}
{% load sass_tags %}
{% block scss %}<link href="{% sass_src 'scss/account.scss' %}" rel="stylesheet" type="text/css"/>{% endblock %}
{% block content %}
<a href="/" class="return-home"><i class="fas fa-arrow-left"></i></a>
<section class="main-form">
    <div class="container-form">
        <h1>{% translate 'Register' %}</h1>
        <form method="post" action="{% url 'user:register' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    <label class="col-6" for="{{field.id_for_label}}">
                        {{ field.label }}
                    </label>
                    {{ field }}
                </div>
            {% endfor %}
            {% if form.errors %}
                <div class="alert alert-danger">
                    {% for key, value in form.errors.items %}
                        <p>{{ value }}</p>
                    {% endfor %}
                </div>
            {% endif %}
            <div class="m-auto">
                <button class="" id="id_register" type="submit">{% translate 'Register' %}</button>
            </div>
        </form>
    </div>
</section>
{% endblock %}