eden_conception/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as v
from django.conf.urls.static import static
from django.views.i18n import JavaScriptCatalog


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('static_page.urls', namespace='static_page')),
    path('', include('user.urls', namespace='user')),
    path('', include('project.urls', namespace='project')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path(
        'reset_password/',
        v.PasswordResetView.as_view(template_name='user/password_reset.html'),
        name='password_reset'),
    path(
        'reset/<uidb64>/<token>/',
        v.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path(
        'reset_password_sent/',
        v.PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),
        name='password_reset_done'),
    path(
        'reset_password_complete/',
        v.PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'),
        name='password_reset_complete'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

project/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as v
from project.views.project_views import ProjectView
from project.views.list_views import ListView
from project.views.task_views import TaskView


app_name = 'project'

urlpatterns = [
    path('dashboard/', login_required(ProjectView.as_view(), login_url='user:login'), name='dashboard'),
    path('create_project/', login_required(ProjectView.create_project, login_url='user:login'), name='create_project'),
    path('delete_project/', login_required(ProjectView.delete_project, login_url='user:login'), name='delete_project'),
    path('add_member/', login_required(ProjectView.add_member, login_url='user:login'), name='add_member'),
    path('update_project/', login_required(ProjectView.update_project, login_url='user:login'), name='update_project'),
    path('<project_id>/update_form/', login_required(ProjectView.as_view(), login_url='user:login'), name='form_update_project'),
    path('get_statistics/', login_required(ProjectView.get_statistics, login_url='user:login'), name='get_statistics'),

    path('project-<int:project_id>/', login_required(ListView.as_view(), login_url='user:login'), name='project'),
    path('create_list/', login_required(ListView.create_list, login_url='user:login'), name='create_list'),
    path('delete_list/', login_required(ListView.delete_list, login_url='user:login'), name='delete_list'),
    path('update_list/', login_required(ListView.update_list, login_url='user:login'), name='update_list'),
    path('<list_id>/update_list_form/', login_required(ListView.as_view(), login_url='user:login'), name='form_update_list'),
    path('create_task/', login_required(ListView.create_task, login_url='user:login'), name='create_task'),
    path('update_order_task/', login_required(ListView.update_order_task, login_url='user:login'), name='update_task'),

    path('project-<int:project_id>/task-<int:task_id>/', login_required(TaskView.as_view(), login_url='user:login'), name='task'),
    path('<task_id>/update/', login_required(TaskView.as_view(), login_url='user:login'), name='form_update_task'),
    path('update_task/', login_required(TaskView.update_task, login_url='user:login'), name='update_task'),
    path('delete_task/', login_required(TaskView.delete_task, login_url='user:login'), name='delete_task'),
]

static_page/urls.py
""" All urls for the static_page application """
from django.urls import path
from . import views


app_name = 'static_page'
urlpatterns = [
    path('', views.IndexView.as_view(), name='homepage'),
    path('legal-notices/', views.LegalNoticeView.as_view(), name="legal_notices")
]

user/urls.py
# django.contrib.auth import urls
from django.db.models import base
from django.urls import path, include
from django.contrib.auth import views as v
from . import views


app_name = 'user'
urlpatterns = [
    path('login/', v.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('register/', views.RegisterView.as_view(), name='register'),
]

static_page/views.py
""" All views in the frontend web application """
from django.shortcuts import render
from django.views import View


class IndexView(View):
    """ Homepage view """

    template_name = 'static_page/index.html'

    def get(self, request):
        return render(request, self.template_name)


class LegalNoticeView(View):
    """ Legal Notice view """

    template_name = 'static_page/legal_notice.html'

    def get(self, request):
        return render(request, self.template_name)

static_page/templates/static_page/base.html
{% load sass_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% block scss %}{% endblock %}
    <link href="{% static 'fontawesome_free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% sass_src 'scss/base_front.scss' %}" rel="stylesheet" type="text/css" />
    <!-- Favicons -->
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'img/favicons/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'img/favicons/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'img/favicons/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/favicons/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'img/favicons/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'img/favicons/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'img/favicons/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'img/favicons/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicons/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'img/favicons/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/favicons/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'img/favicons/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'img/favicons/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">
</head>
<body>
    <header>
        <div class="door">
            {% if user.is_authenticated %}
                <a href="{% url 'project:dashboard' %}">
                    <i class="fas fa-door-open"></i>
                </a>
            {% else %}
                <a href="{% url 'user:login' %}">
                    <i class="fas fa-door-closed"></i>
                </a>
            {% endif %}
        </div>
        {% block content %}{% endblock %}
    </header>
    {% block js %}{% endblock %}
</body>
</html>

static_page/templates/static_page/index.html
{% extends 'static_page/base.html' %}
{% load i18n %}
{% load sass_tags %}
{% load static %}
{% block title %}Eden Conception{% endblock %}
{% block scss %}<link href="{% sass_src 'scss/index.scss' %}" rel="stylesheet" type="text/css" />{% endblock %}

{% block content %}

    <div class="container">
        <img src="{% static 'img/logo_white.png' %}" alt="Logo Eden Conception"/>
    </div>
    <nav>
        <ul>
            <li>
                <a href="{% url 'user:login' %}">{% translate 'Connection' %}</a>
            </li>
            <li>
                <a href="{% url 'static_page:legal_notices' %}">{% translate 'Legals mentions' %}</a>
            </li>
        </ul>
    </nav>
{% endblock %}
{% block js %}
<script type="module" src="{% static 'js/three.js' %}"></script>
{% endblock %}

static_page/templates/static_page/legal_notice.html
{% extends 'static_page/base.html' %}
{% load i18n %}
{% load sass_tags %}
{% block scss %}<link href="{% sass_src 'scss/legal_notice.scss' %}" rel="stylesheet" type="text/css" />{% endblock %}
{% block content %}
<a href="/" class="return-home"><i class="fas fa-arrow-left"></i></a>
<section class="main-legal-notice">
    <div class="container-legal-notice">
        <h1>{% translate 'Legal notices' %}</h1>
        <article>
            <h2>{% translate 'Legal informations' %}</h2>
            <p>{% translate 'Under Article 6 of Law No. 2004-575 of June 21, 2004 on confidence in the digital economy, users of the eden-conception.fr site are informed of the identity of the various shareholders within the framework of its realization and its follow-up:' %}</p>
            <p>{% translate 'In accordance with the "Informatique et Libertés" law of January 6, 1978, this site is the subject of a declaration to the CNIL - dated November 19, 2015 - receipt of declaration n ° 190 6255' %}</p>
        </article>
        <article>
            <h2>{% translate 'Owner' %}</h2>
            <p>Elodie Meunier</p>
        </article>
        <article>
            <h2>{% translate 'Brand' %}</h2>
            <p>"Eden Conception"</p>
        </article>
        <article>
            <h2>Designer / Webhost</h2>
            <p>Eden conception</p>
        </article>
    </div>
</section>
{% endblock %}