eden_conception/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as v
from django.conf.urls.static import static
from django.views.i18n import JavaScriptCatalog


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('static_page.urls', namespace='static_page')),
    path('', include('user.urls', namespace='user')),
    path('', include('project.urls', namespace='project')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path(
        'reset_password/',
        v.PasswordResetView.as_view(template_name='user/password_reset.html'),
        name='password_reset'),
    path(
        'reset/<uidb64>/<token>/',
        v.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path(
        'reset_password_sent/',
        v.PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),
        name='password_reset_done'),
    path(
        'reset_password_complete/',
        v.PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'),
        name='password_reset_complete'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

project/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as v
from project.views.project_views import ProjectView
from project.views.list_views import ListView
from project.views.task_views import TaskView


app_name = 'project'

urlpatterns = [
    path('dashboard/', login_required(ProjectView.as_view(), login_url='user:login'), name='dashboard'),
    path('create_project/', login_required(ProjectView.create_project, login_url='user:login'), name='create_project'),
    path('delete_project/', login_required(ProjectView.delete_project, login_url='user:login'), name='delete_project'),
    path('add_member/', login_required(ProjectView.add_member, login_url='user:login'), name='add_member'),
    path('update_project/', login_required(ProjectView.update_project, login_url='user:login'), name='update_project'),
    path('<project_id>/update_form/', login_required(ProjectView.as_view(), login_url='user:login'), name='form_update_project'),
    path('get_statistics/', login_required(ProjectView.get_statistics, login_url='user:login'), name='get_statistics'),

    path('project-<int:project_id>/', login_required(ListView.as_view(), login_url='user:login'), name='project'),
    path('create_list/', login_required(ListView.create_list, login_url='user:login'), name='create_list'),
    path('delete_list/', login_required(ListView.delete_list, login_url='user:login'), name='delete_list'),
    path('update_list/', login_required(ListView.update_list, login_url='user:login'), name='update_list'),
    path('<list_id>/update_list_form/', login_required(ListView.as_view(), login_url='user:login'), name='form_update_list'),
    path('create_task/', login_required(ListView.create_task, login_url='user:login'), name='create_task'),
    path('update_order_task/', login_required(ListView.update_order_task, login_url='user:login'), name='update_task'),

    path('project-<int:project_id>/task-<int:task_id>/', login_required(TaskView.as_view(), login_url='user:login'), name='task'),
    path('<task_id>/update/', login_required(TaskView.as_view(), login_url='user:login'), name='form_update_task'),
    path('update_task/', login_required(TaskView.update_task, login_url='user:login'), name='update_task'),
    path('delete_task/', login_required(TaskView.delete_task, login_url='user:login'), name='delete_task'),
]

user/urls.py
# django.contrib.auth import urls
from django.db.models import base
from django.urls import path, include
from django.contrib.auth import views as v
from . import views


app_name = 'user'
urlpatterns = [
    path('login/', v.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('register/', views.RegisterView.as_view(), name='register'),
]

project/models.py
from django.db import models
from django.db.models import F
from django.utils.timezone import now
from user.models import User


class ProjectManager(models.Manager):

    def add_member(self, email, project):
        user = User.objects.filter(email__contains=email)
        import pdb; pdb.set_trace();

        if not user.exists():
            return

        project.user_ids.add(user.get().id)
        return True


class Project(models.Model):

    name = models.CharField(max_length=120, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='main_user')
    user_ids = models.ManyToManyField(User, related_name='member')
    created_at = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    number_task = models.IntegerField(default=0)

    objects = models.Manager()
    objects_project = ProjectManager()

    @property
    def get_number_task(self):
        self.number_task = 0
        project_lists = self.list_set.all()
        for li in project_lists:
            self.number_task += li.task_set.all().count()

        return self.number_task

    def save(self, *args, **kwargs):
        self.number_task = self.get_number_task
        super(Project, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['created_at']


class List(models.Model):

    name = models.CharField(max_length=100)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class TaskManager(models.Manager):

    def get_index(self, current_list):
        index = 0
        if current_list.task_set.all().count() > 0:
            index = current_list.task_set.all().reverse()[0].index + 1

        next_tasks = Task.objects.filter(index__gte=index)
        next_tasks.update(index=F('index') + 1)

        return index

    def _format_value(self, value):
        if isinstance(value, float) or isinstance(value, int):
            hours, minutes = divmod(abs(value) * 60, 60)
            minutes = round(minutes)
            if minutes == 60:
                minutes = 0
                hours += 1

            if value < 0:
                return '-%02d:%02d' % (hours, minutes)
        return '%02d:%02d' % (hours, minutes)

    def update_order_task(self, datas):
        for data in datas:
            current_task = Task.objects.get(id=data['task_id'])
            current_task.project_list = List.objects.get(id=data['list_id'])
            current_task.index = data['index']
            current_task.save()


class Task(models.Model):

    name = models.CharField(max_length=120)
    description = models.TextField()
    project_list = models.ForeignKey(List, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    assigned_to = models.ForeignKey(User, on_delete=models.CASCADE)
    deadline = models.DateField(blank=True, null=True)
    index = models.IntegerField(db_index=True)
    planned_hours = models.FloatField(default=0)
    effective_hours = models.FloatField(default=0)
    remaining_hours = models.FloatField(default=0)

    objects = models.Manager()
    objects_task = TaskManager()

    @property
    def planned_hours_time(self):
        return Task.objects_task._format_value(self.planned_hours)

    @property
    def effective_hours_time(self):
        timesheets = self.timesheet_set.all()
        total_effective_hours = sum(timesheet.unit_hour for timesheet in timesheets)
        return Task.objects_task._format_value(total_effective_hours)

    @property
    def remaining_hours_time(self):
        timesheets = self.timesheet_set.all()
        total_effective_hours = sum(timesheet.unit_hour for timesheet in timesheets)
        remaining_hours = self.planned_hours - total_effective_hours

        return Task.objects_task._format_value(remaining_hours)

    class Meta:
        ordering = ['index']

project/views/list_views.py
""" All views for the model list """
import json
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.utils.translation import gettext_lazy as _

from project.forms.list_forms import CreateListForm, UpdateListForm
from project.forms.task_forms import CreateTaskForm
from project.models.project import Project
from project.models.list import List
from project.models.task import Task
from user.models import User


class ListView(View):
    ''' Class to manage all interactions and views with the lists '''

    template_name = 'project/lists/lists.html'
    form = CreateListForm

    def get(self, request, project_id):
        ''' Method to view all lists of project choosen. '''

        project = get_object_or_404(Project, pk=project_id)
        lists = project.list_set.all()

        context = {
            'project': project,
            'lists': lists,
            'create_list_form': self.form,
            'create_task_form': CreateTaskForm
        }
        return render(request, self.template_name, context)

    def post(self, request, list_id):
        ''' Method post to display the form
            to update a list.
        '''
        res = {}
        if request.method == 'POST':
            current_list = List.objects.get(id=list_id)
            datas = {'name': current_list.name}

            form_update = UpdateListForm(instance=current_list, initial=datas)
            context = {'form_update': form_update, 'list': current_list}
            res['list_id'] = list_id
            res['template'] = render_to_string(
                template_name='project/lists/forms/update_list.html',
                context=context,
                request=request
            )

        return JsonResponse(res)

    @classmethod
    def create_list(cls, request):
        ''' method to create a list.'''
        res = {}
        context = {}
        form = cls.form(request.POST)
        if form.is_valid():
            name = form.cleaned_data['list_name']
            project = Project.objects.get(id=request.POST.get('project_id'))

            new_list = List.objects.create(
                name=name,
                project=project,
            )
            project.save()

            context['new_list'] = new_list
            context['create_task_form'] = CreateTaskForm

            res['list_name'] = name
            res['list_id'] = new_list.id
            res['template'] = render_to_string(
                template_name='project/lists/new_list.html',
                context=context,
                request=request
            )
        else:
            res['error'] = _('Please, write a list name.')

        return JsonResponse(res)

    @staticmethod
    def delete_list(request):
        ''' method to delete a list.'''
        res = {}
        if request.method == 'POST':
            list_to_delete = List.objects.get(id=request.POST.get('list_id'))
            project = Project.objects.get(id=list_to_delete.project_id)

            list_to_delete.delete()
            project.save()

            res['list_id'] = request.POST.get('list_id')
            res['success'] = _('The list has been deleted')
        else:
            res['error'] = _('The list doesn\'t have deleted')

        return JsonResponse(res)

    @staticmethod
    def create_task(request):
        ''' method to create a task.'''
        res = {}
        if request.method == 'POST':
            user = User.objects.get(id=request.user.id)
            name = request.POST.get('task_name')
            list_id = request.POST.get('list_id')
            current_list = List.objects.get(id=int(list_id))
            project = Project.objects.get(id=current_list.project_id)

            index = Task.objects_task.get_index(current_list)
            new_task = Task.objects.create(
                name=name,
                project_list=current_list,
                assigned_to=user,
                deadline=None,
                index=index,
                planned_hours=0.0,
            )
            project.save()

            context = {'task': new_task, 'project': project}

            res['task_name'] = name
            res['task_id'] = new_task.id
            res['list_id'] = list_id
            res['template'] = render_to_string('project/tasks/new_task.html', context)

        return JsonResponse(res)

    @staticmethod
    def update_order_task(request):
        ''' method to update the order of task.
            Called when we drag and drop a task into
            an another list.
        '''
        res = {}
        if request.method == 'POST':
            datas = json.loads(request.POST.get('datas'))
            Task.objects_task.update_order_task(datas)

        return JsonResponse(res)

    @staticmethod
    def update_list(request):
        ''' Method to update the name of list. '''
        res = {}
        if request.method == 'POST':
            current_list = List.objects.get(id=request.POST.get('list_id'))

            # Update list
            current_list.name = request.POST.get('name')
            current_list.save()

            res['list_id'] = current_list.id
            res['list_name'] = current_list.name

        return JsonResponse(res)

project/views/task_views.py
""" All views for the model task """
from datetime import datetime
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.utils.translation import gettext_lazy as _

from project.forms.task_forms import UpdateTaskForm
from project.models.project import Project
from project.models.task import Task
from user.models import User
from timesheet.views.timesheet_views import TimesheetView


class TaskView(View):
    ''' Class to manage all interactions and views with the tasks. '''
    template_name = 'project/tasks/tasks.html'

    def get(self, request, project_id, task_id):
        ''' Method to view the detail of a task. '''
        project = get_object_or_404(Project, pk=project_id)
        task = get_object_or_404(Task, pk=task_id)
        context = {'project': project, 'task': task}

        return render(request, self.template_name, context)

    def post(self, request, task_id):
        ''' Method to display the form to update one task '''
        res = {}
        if request.method == 'POST':
            current_task = Task.objects.get(id=task_id)
            datas = {
                'name': current_task.name,
                'assigned_to': current_task.assigned_to,
                'deadline': current_task.deadline,
                'description': current_task.description,
                'planned_hours': current_task.planned_hours
            }

            form_update = UpdateTaskForm(instance=current_task, initial=datas)
            context = {
                'form_update': form_update,
                'formset': TimesheetView.create_formset(current_task),
                'task': current_task
            }

            res['task_id'] = task_id
            res['template'] = render_to_string(
                template_name='project/tasks/forms/update_task.html',
                context=context,
                request=request
            )

        return JsonResponse(res)

    @staticmethod
    def update_task(request):
        ''' Method to update a task. '''
        res = {}
        if request.method == 'POST':
            current_task = Task.objects.get(id=request.POST.get('task_id'))
            formset = TimesheetView.update_timesheet(request)

            if formset is not True:
                formset_clean = [i for i in formset if i]
                if formset_clean:
                    res['error'] = formset_clean[0]

            # Convert time to float
            convert_in_time = datetime.strptime(request.POST.get('planned_hours'), '%H:%M').time()
            planned_hours_float = convert_in_time.hour + convert_in_time.minute / 60.0

            # Update task
            current_task.name = request.POST.get('name')
            current_task.assigned_to = User.objects.get(id=request.POST.get('assigned_to'))
            current_task.deadline = datetime.strptime(request.POST.get('deadline'), '%d/%m/%Y')
            current_task.description = request.POST.get('description')
            current_task.planned_hours = planned_hours_float
            current_task.save()

            context = {'task': current_task}

            res['task_id'] = current_task.id
            res['template'] = render_to_string('project/tasks/task_detail.html', context)

        return JsonResponse(res)

    @staticmethod
    def delete_task(request):
        ''' Method to delete a task. '''
        res = {}
        if request.method == 'POST':
            task_to_delete = Task.objects.get(id=request.POST.get('task_id'))
            project = Project.objects.get(id=task_to_delete.project_list.project_id)

            task_to_delete.delete()
            project.save()

            res['task_id'] = request.POST.get('task_id')
            res['project_id'] = project.id
            res['success'] = _('The task has been deleted')
        else:
            res['error'] = _('The task doesn\'t have deleted')

        return JsonResponse(res)

project/templates/project/tasks/new_task.html
{% if task %}
<div class="container-project-task" id="project-task-{{task.id}}" task-id="{{task.id}}">
    <a href="{% url 'project:task' project_id=project.id task_id=task.id %}">{{task.name}}</a>
</div>
{% endif %}

project/templates/project/tasks/task_detail.html
{% load i18n %}
<div class="contain-header-info">
    <div id="task-modal" class="modal"></div>
    <h1>{{task.name}}</h1>
    <div class="header-task">
        <button id="update-task" task-id="{{task.id}}">{% translate 'Update' %}</button>
        <button type="button" id="delete-task" task-id="{{task.id}}">{% translate 'Delete' %}</button>
    </div>
    <div class="container-task">
        <div class="container-info-task">
    
            <div class="form-group">
                <label class="" for="id_assigned_to">
                    {% translate 'Assigned to ' %} 
                </label>
                <span>{{task.assigned_to}}</span>
            </div>
            <div class="form-group">
                <label class="" for="id_deadline">
                    {% translate 'Deadline ' %} 
                </label>
                <span>{{task.deadline.day}}/{{task.deadline.month}}/{{task.deadline.year}}</span>
            </div>
            <div class="form-group">
                <label class="" for="id_description">
                    {% translate 'Description ' %}
                </label>
                <div class="task_description">{{task.description |linebreaks}}</div>
            </div>
            <div class="form-group">
                <label class="" for="id_planned_hours">
                    {% translate 'Planned hours ' %}
                </label>
                <span>{{task.planned_hours_time}}</span>
            </div>
            <div class="form-group">
                <table>
                    <thead>
                        <tr>
                            <th>{% translate 'Created at' %}</th>
                            <th>{% translate 'User' %}</th>
                            <th>{% translate 'Description' %}</th>
                            <th>{% translate 'Unit hour' %}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for timesheet_line in task.timesheet_set.all %}
                            {% if timesheet_line %}
                                <tr class="no-update">
                                    <td>{{timesheet_line.created_at.day}}/{{timesheet_line.created_at.month}}/{{timesheet_line.created_at.year}}</td>
                                    <td>{{timesheet_line.user}}</td>
                                    <td>{{timesheet_line.description}}</td>
                                    <td>{{timesheet_line.unit_hour_time}}</td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="form-group">
                <label class="" for="id_deadline">
                    {% translate 'Effective hours ' %} 
                </label>
                <span>{{task.effective_hours_time}}</span>
            </div>
            <div class="form-group">
                <label class="" for="id_deadline">
                    {% translate 'Remaining hours ' %} 
                </label>
                <span>{{task.remaining_hours_time}}</span>
            </div>
        </div>
    </div>
</div>

project/templates/project/tasks/tasks.html
{% extends 'project/base.html' %}
{% load i18n %}
{% load sass_tags %}
{% load static %}
{% block title %}{{project.name}}{% endblock %}
{% block scss %}
    <link href="{% sass_src 'scss/tasks.scss' %}" rel="stylesheet" type="text/css" />
{% endblock %}
{% block content %}
    <main>
        <div id="main-task">
            <div class="return-dashboard">
                <a href="{% url 'project:project' project_id=project.id %}" ><i class="fas fa-arrow-left"></i></a>
                <a href="{% url 'project:dashboard' %}"><i class="fas fa-chart-line"></i></a>
            </div>
            {% include 'project/tasks/task_detail.html' %}
        </div>
        <div id="main-messages"></div>
    </main>
{% endblock %}
{% block js %}
    <script src="{% static 'js/submit_form_ajax.js' %}"></script>
    <script src="{% static 'js/tasks/update_task.js' %}"></script>
    <script src="{% static 'js/tasks/delete_task.js' %}"></script>
{% endblock %}